In [1]:
from joblib import dump, load
import pandas as pd
import numpy as np
import bamboolib

In [2]:
#import best regression model to predict 2021
clf = load("random_forest_clf.joblib")

In [49]:
#import traning data t-1 for labels in 2021 at t
data_2016_x = pd.read_csv('x_df_2016_data.csv')
#x_attributes = pd.read_csv('x_shape_mould.csv')

data_2016_x

,Unnamed: 0,lga,Adelie Land (France),Afghanistan,Albania,Algeria,"Americas, nfd",Andorra,Angola,Anguilla,...,Not stated,Other Religions,Advanced Diploma and Diploma Level,Bachelor Degree Level,Certificate Level,Graduate Diploma and Graduate Certificate Level,Level of education inadequately described,Level of education not stated,Not applicable,Postgraduate Degree Level
0,1243,Albury (C),0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4496,397,3530.0,4704.0,9864.0,843.0,307.0,4257.0,26523.0,1043
1,1244,Armidale Regional (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2875,175,1729.0,3285.0,4317.0,575.0,186.0,2629.0,14984.0,1740
2,1245,Ballina (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4035,205,3327.0,4736.0,7752.0,745.0,333.0,3806.0,20021.0,1068
3,1246,Balranald (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,287,4,83.0,94.0,297.0,17.0,6.0,290.0,1481.0,24
4,1247,Bathurst Regional (A),0.0,10.0,0.0,5.0,0.0,0.0,0.0,0.0,...,4453,180,2672.0,3753.0,7859.0,652.0,253.0,4257.0,20911.0,951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,1792,Migratory - Offshore - Shipping (NT),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8,0,5.0,15.0,20.0,0.0,4.0,12.0,11.0,0
550,1793,Unincorporated ACT,0.0,472.0,19.0,45.0,0.0,0.0,13.0,0.0,...,33883,3700,29723.0,71606.0,43558.0,13404.0,2539.0,23685.0,177549.0,34785
551,1794,Migratory - Offshore - Shipping (ACT),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
552,1795,Unincorp. Other Territories,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,786,47,270.0,324.0,759.0,55.0,28.0,835.0,2184.0,78
553,1796,Migratory - Offshore - Shipping (OT),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0

In [50]:
#separate the lga names from the data

#x_2016 = result1.iloc[:604,:]
X_a = data_2016_x.iloc[:,2:]
lgas = data_2016_x.iloc[:,:2]
X = X_a.dropna(how='any', axis=1)
X = X_a.astype(np.float32)
np.any(np.isnan(X))

False

In [51]:
predictions_2021 = clf.predict(X)

In [52]:
predictions_2021.shape

(554, 265)

In [53]:
#get the column names and add them to the predictions_2021 numpy array
data_y = pd.read_csv("y_2016.csv")
data_y = data_y.drop(columns=['Unnamed: 0'])
data_y =  data_y.iloc[:,1:]
data_y = data_y.loc[:0,:]
#data_y = pd.concat([data_y, predictions_2021], ignore_index=True, sort=False)
df_predictions = pd.DataFrame(data=predictions_2021, columns=[list(data_y)])

In [54]:
df_predictions.columns = ["_".join([str(index) for index in multi_index]) for multi_index in df_predictions.columns.ravel()]
df_predictions

,Adelie Land (France),Afghanistan,Albania,Algeria,"Americas, nfd",Andorra,Angola,Anguilla,"Antarctica, nfd",Antigua and Barbuda,...,Vanuatu,"Virgin Islands, British","Virgin Islands, United States",Wales,Wallis and Futuna,"Western Europe, nfd",Western Sahara,Yemen,Zambia,Zimbabwe
0,0.0,41.347059,0.152941,0.988235,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.582353,0.000000,0.0,40.588235,0.000000,0.0,0.0,0.094118,16.329412,30.758824
1,0.0,13.194118,0.411765,0.611765,0.000000,0.000000,0.041176,0.0,0.000000,0.000000,...,1.117647,0.000000,0.0,22.935294,0.000000,0.0,0.0,0.905882,4.358824,28.064706
2,0.0,0.682353,0.000000,0.405882,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.464706,0.000000,0.0,48.641176,0.000000,0.0,0.0,0.035294,7.388235,38.629412
3,0.0,0.105882,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.035294,0.000000,0.0,0.935294,0.000000,0.0,0.0,0.000000,0.105882,1.217647
4,0.0,7.947059,0.611765,1.223529,0.000000,0.000000,0.035294,0.0,0.000000,0.000000,...,0.917647,0.000000,0.0,21.882353,0.000000,0.0,0.0,0.017647,5.488235,26.929412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.035294,0.723529
550,0.0,771.958824,24.517647,51.858824,0.070588,1.041176,15.458824,0.0,0.141176,0.382353,...,36.441176,0.329412,0.0,534.558824,0.788235,0.0,0.0,25.411765,171.441176,910.070588
551,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.264706
552,0.0,16.058824,0.035294,0.200000,0.000000,0.000000,0.035294,0.0,0.000000,0.000000,...,5.582353,0.000000,0.0,2.088235,0.000000,0.0,0.0,0.052941,2.000000,9.141176
553,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.017647,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.264706

In [55]:
lgas = lgas.drop(columns=['Unnamed: 0'])

In [56]:
lga = lgas["lga"]
df_predictions = df_predictions.join(lga)
df_predictions = df_predictions[['lga'] + [x for x in df_predictions.columns if x not in ['lga']]]
df_predictions

,lga,Adelie Land (France),Afghanistan,Albania,Algeria,"Americas, nfd",Andorra,Angola,Anguilla,"Antarctica, nfd",...,Vanuatu,"Virgin Islands, British","Virgin Islands, United States",Wales,Wallis and Futuna,"Western Europe, nfd",Western Sahara,Yemen,Zambia,Zimbabwe
0,Albury (C),0.0,41.347059,0.152941,0.988235,0.000000,0.000000,0.000000,0.0,0.000000,...,0.582353,0.000000,0.0,40.588235,0.000000,0.0,0.0,0.094118,16.329412,30.758824
1,Armidale Regional (A),0.0,13.194118,0.411765,0.611765,0.000000,0.000000,0.041176,0.0,0.000000,...,1.117647,0.000000,0.0,22.935294,0.000000,0.0,0.0,0.905882,4.358824,28.064706
2,Ballina (A),0.0,0.682353,0.000000,0.405882,0.000000,0.000000,0.000000,0.0,0.000000,...,0.464706,0.000000,0.0,48.641176,0.000000,0.0,0.0,0.035294,7.388235,38.629412
3,Balranald (A),0.0,0.105882,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.035294,0.000000,0.0,0.935294,0.000000,0.0,0.0,0.000000,0.105882,1.217647
4,Bathurst Regional (A),0.0,7.947059,0.611765,1.223529,0.000000,0.000000,0.035294,0.0,0.000000,...,0.917647,0.000000,0.0,21.882353,0.000000,0.0,0.0,0.017647,5.488235,26.929412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,Migratory - Offshore - Shipping (NT),0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.035294,0.723529
550,Unincorporated ACT,0.0,771.958824,24.517647,51.858824,0.070588,1.041176,15.458824,0.0,0.141176,...,36.441176,0.329412,0.0,534.558824,0.788235,0.0,0.0,25.411765,171.441176,910.070588
551,Migratory - Offshore - Shipping (ACT),0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.264706
552,Unincorp. Other Territories,0.0,16.058824,0.035294,0.200000,0.000000,0.000000,0.035294,0.0,0.000000,...,5.582353,0.000000,0.0,2.088235,0.000000,0.0,0.0,0.052941,2.000000,9.141176
553,Migratory - Offshore - Shipping (OT),0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.017647,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.264706

In [11]:
#df_predictions

In [57]:
df_predictions.to_csv("2021_predictions.csv")

In [58]:
print(df_predictions.shape)
# print COB data from 2006, 2011 and 2016
y_2006 = pd.read_csv("y_2006.csv")
y_2011 = pd.read_csv("y_2011.csv")
y_2016 = pd.read_csv("y_2016.csv")
y_2006 = y_2006.drop(columns=['Unnamed: 0'])
y_2011 = y_2011.drop(columns=['Unnamed: 0'])
y_2016 = y_2016.drop(columns=['Unnamed: 0'])
#create a percentage style data for 2006,2011,2016 and 2021
print(y_2006.shape)
print(y_2011.shape)
print(y_2016.shape)

(554, 266)
(572, 266)
(577, 266)
(685, 266)

In [67]:
percentages_2021 = df_predictions

In [66]:
total_2021 = percentages_2021.sum(axis=1,numeric_only = True)
total_2021
#total_2021 = percentages_2021["total"]

0       53603.882353
1       30709.470588
2       43117.535294
3        2263.005882
4       42580.617647
           ...
549       212.670588
550    424250.894118
551        95.982353
552      5545.817647
553        97.888235
Length: 554, dtype: float64

In [63]:
percentages_2021 = percentages_2021.iloc[:,1:].div(total_2021,axis = 0)
percentages_2021

,Adelie Land (France),Afghanistan,Albania,Algeria,"Americas, nfd",Andorra,Angola,Anguilla,"Antarctica, nfd",Antigua and Barbuda,...,Vanuatu,"Virgin Islands, British","Virgin Islands, United States",Wales,Wallis and Futuna,"Western Europe, nfd",Western Sahara,Yemen,Zambia,Zimbabwe
0,0.0,0.000771,0.000003,0.000018,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,...,0.000011,0.000000e+00,0.0,0.000757,0.000000,0.0,0.0,1.755799e-06,0.000305,0.000574
1,0.0,0.000430,0.000013,0.000020,0.000000e+00,0.000000,1.340839e-06,0.0,0.000000e+00,0.000000e+00,...,0.000036,0.000000e+00,0.0,0.000747,0.000000,0.0,0.0,2.949847e-05,0.000142,0.000914
2,0.0,0.000016,0.000000,0.000009,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,...,0.000011,0.000000e+00,0.0,0.001128,0.000000,0.0,0.0,8.185560e-07,0.000171,0.000896
3,0.0,0.000047,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,...,0.000016,0.000000e+00,0.0,0.000413,0.000000,0.0,0.0,0.000000e+00,0.000047,0.000538
4,0.0,0.000187,0.000014,0.000029,0.000000e+00,0.000000,8.288775e-07,0.0,0.000000e+00,0.000000e+00,...,0.000022,0.000000e+00,0.0,0.000514,0.000000,0.0,0.0,4.144388e-07,0.000129,0.000632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,...,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000166,0.003402
550,0.0,0.001820,0.000058,0.000122,1.663832e-07,0.000002,3.643793e-05,0.0,3.327665e-07,9.012425e-07,...,0.000086,7.764551e-07,0.0,0.001260,0.000002,0.0,0.0,5.989796e-05,0.000404,0.002145
551,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,...,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000,0.002758
552,0.0,0.002896,0.000006,0.000036,0.000000e+00,0.000000,6.364096e-06,0.0,0.000000e+00,0.000000e+00,...,0.001007,0.000000e+00,0.0,0.000377,0.000000,0.0,0.0,9.546144e-06,0.000361,0.001648
553,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,...,0.000180,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000,0.002704

In [89]:

percentages_2021.to_csv("2021_predictions_pct.csv")

In [ ]:

total_2006 = y_2006.sum(axis=1,numeric_only = True)
total_2011 = y_2011.sum(axis=1,numeric_only = True)
total_2016 = y_2016.sum(axis=1,numeric_only = True)
#total_2006 = np.array(total_2006)
#for i in range(len(total_2006)):
 #   if total_2006[i] == 0:
 #       total_2006[i] = 1

percentages_2006 = y_2006.iloc[:,1:].div(total_2006,axis = 0)
percentages_2006
#percentages_2011 = y_2011.iloc[:,1:].div(total_2011,axis = 0)
#percentages_2016 = y_2016.iloc[:,1:].div(total_2016,axis = 0)