In [1]:
#import lazypredict
#from lazypredict.Supervised import LazyRegressor
import pandas as pd
import numpy as np
import bamboolib
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.dummy import DummyRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from xgboost import XGBRegressor
from sklearn.svm import SVR
from sklearn.metrics import r2_score

In [66]:
data_2006_x = pd.read_csv('../Model_training/x_df_2006_data.csv')
data_2006_y = pd.read_csv('y_for_2006_data2011.csv')
data_2011_x = pd.read_csv('x_df_2011_data.csv')
data_2011_y = pd.read_csv('y_for_2011_data2016.csv')
data_2016_x = pd.read_csv('x_df_2016_data.csv')

In [3]:
data_2006_x = data_2006_x.dropna(how='any', axis=1)
data_2006_x

,Unnamed: 0,lga,Adelie Land (France)_x,Afghanistan_x,Albania_x,Algeria_x,"Americas, nfd_x",Andorra_x,Angola_x,Anguilla_x,...,Not stated_x_3,Other Religions,Advanced Diploma and Diploma Level,Bachelor Degree Level,Certificate Level,Graduate Diploma and Graduate Certificate Level,Level of education inadequately described,Level of education not stated,Not applicable,Postgraduate Degree Level
0,0,Albury (C),0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,...,4284,138,2371.0,3351.0,7381.0,571.0,587.0,4048.0,27512.0,458.0
1,1,Armidale Dumaresq (A),0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2319,135,1284.0,2351.0,2976.0,351.0,312.0,1833.0,13225.0,1046.0
2,2,Ashfield (A),0.0,4.0,0.0,8.0,0.0,0.0,0.0,0.0,...,4696,281,2715.0,6604.0,3396.0,697.0,559.0,4598.0,18417.0,2675.0
3,3,Ballina (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3515,164,2350.0,3207.0,6163.0,473.0,612.0,3202.0,21911.0,553.0
4,4,Balranald (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,271,3,69.0,90.0,245.0,16.0,19.0,257.0,1741.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,508,Darwin (C),0.0,0.0,0.0,3.0,0.0,0.0,4.0,0.0,...,10076,390,3807.0,6773.0,9420.0,1106.0,730.0,7459.0,35274.0,1716.0
509,509,Katherine (T),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1692,50,366.0,513.0,1243.0,78.0,81.0,1257.0,4596.0,58.0
510,510,Palmerston (C),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4241,92,1110.0,1145.0,3712.0,202.0,197.0,2644.0,14535.0,168.0
511,511,Unincorporated NT,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,...,6468,2338,709.0,920.0,2598.0,142.0,159.0,4436.0,21427.0,131.0
512,512,Unincorporated ACT,0.0,233.0,12.0,13.0,0.0,0.0,15.0,0.0,...,33012,2107,22011.0,51544.0,34489.0,9176.0,3963.0,21236.0,163088.0,17823.0

In [4]:
data_2011_x = data_2011_x.dropna(how='any', axis=1)
data_2011_x

,Unnamed: 0,lga,Adelie Land (France)_x,Afghanistan_x,Albania_x,Algeria_x,"Americas, nfd_x",Andorra_x,Angola_x,Anguilla_x,...,Not stated_x_3,Other Religions,Advanced Diploma and Diploma Level,Bachelor Degree Level,Certificate Level,Graduate Diploma and Graduate Certificate Level,Level of education inadequately described,Level of education not stated,Not applicable,Postgraduate Degree Level
0,0,Albury (C),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3682,207,2771.0,4052.0,8497.0,697.0,486.0,3819.0,26734.0,758
1,1,Ballina (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2840,195,2716.0,3948.0,6824.0,551.0,565.0,2979.0,20972.0,715
2,2,Balranald (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,247,0,70.0,89.0,287.0,13.0,22.0,227.0,1568.0,7
3,3,Bathurst Regional (A),0.0,3.0,0.0,7.0,0.0,0.0,0.0,0.0,...,3474,141,2095.0,3132.0,6828.0,466.0,448.0,3504.0,21354.0,689
4,4,Bega Valley (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2782,155,1942.0,2473.0,5961.0,518.0,419.0,2618.0,17593.0,427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,502,Palmerston (C),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3464,131,1573.0,1585.0,5133.0,273.0,214.0,2484.0,16144.0,289
503,503,Wagait (S),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,31,0,17.0,50.0,76.0,8.0,6.0,32.0,169.0,9
504,504,Unincorporated NT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1707,49,460.0,643.0,1501.0,111.0,71.0,1483.0,3668.0,155
505,505,Unincorporated ACT,0.0,345.0,20.0,32.0,0.0,0.0,17.0,0.0,...,26924,2767,26046.0,61827.0,39035.0,11142.0,4720.0,18708.0,169420.0,25686
506,506,Unincorp. Other Territories,0.0,112.0,0.0,0.0,0.0,0.0,0.0,0.0,...,911,59,128.0,159.0,332.0,32.0,22.0,987.0,1317.0,33

In [5]:
data_2016_x = data_2016_x.dropna(how='any', axis=1)
data_2016_x

,Unnamed: 0,lga,Adelie Land (France),Afghanistan,Albania,Algeria,"Americas, nfd",Andorra,Angola,Anguilla,...,Not stated,Other Religions,Advanced Diploma and Diploma Level,Bachelor Degree Level,Certificate Level,Graduate Diploma and Graduate Certificate Level,Level of education inadequately described,Level of education not stated,Not applicable,Postgraduate Degree Level
0,1243,Albury (C),0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4496,397,3530.0,4704.0,9864.0,843.0,307.0,4257.0,26523.0,1043
1,1244,Armidale Regional (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2875,175,1729.0,3285.0,4317.0,575.0,186.0,2629.0,14984.0,1740
2,1245,Ballina (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4035,205,3327.0,4736.0,7752.0,745.0,333.0,3806.0,20021.0,1068
3,1246,Balranald (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,287,4,83.0,94.0,297.0,17.0,6.0,290.0,1481.0,24
4,1247,Bathurst Regional (A),0.0,10.0,0.0,5.0,0.0,0.0,0.0,0.0,...,4453,180,2672.0,3753.0,7859.0,652.0,253.0,4257.0,20911.0,951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,1792,Migratory - Offshore - Shipping (NT),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8,0,5.0,15.0,20.0,0.0,4.0,12.0,11.0,0
550,1793,Unincorporated ACT,0.0,472.0,19.0,45.0,0.0,0.0,13.0,0.0,...,33883,3700,29723.0,71606.0,43558.0,13404.0,2539.0,23685.0,177549.0,34785
551,1794,Migratory - Offshore - Shipping (ACT),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
552,1795,Unincorp. Other Territories,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,786,47,270.0,324.0,759.0,55.0,28.0,835.0,2184.0,78
553,1796,Migratory - Offshore - Shipping (OT),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0

In [6]:
data_2006_y

,Unnamed: 0,Adelie Land (France)_y,Afghanistan_y,Albania_y,Algeria_y,"Americas, nfd_y",Andorra_y,Angola_y,Anguilla_y,"Antarctica, nfd_y",...,Vanuatu_y,"Virgin Islands, British_y","Virgin Islands, United States_y",Wales_y,Wallis and Futuna_y,"Western Europe, nfd_y",Western Sahara_y,Yemen_y,Zambia_y,Zimbabwe_y
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,44.0,0.0,0.0,0.0,0.0,10.0,30.0
1,1,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,15.0
2,2,0.0,10.0,3.0,9.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,3.0,22.0
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,63.0,0.0,0.0,0.0,0.0,4.0,24.0
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,508,0.0,174.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,...,20.0,0.0,0.0,77.0,0.0,0.0,0.0,4.0,29.0,253.0
509,509,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,3.0,38.0
510,510,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,3.0,33.0
511,511,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,21.0
512,512,0.0,345.0,20.0,32.0,0.0,0.0,17.0,0.0,0.0,...,23.0,0.0,0.0,441.0,0.0,0.0,0.0,26.0,100.0,538.0

## Dummy classifier for time series

In [8]:
#join 2006 and 2011 data
data_x = [data_2006_x, data_2011_x]
x = pd.concat(data_x)
x = x.dropna(how={'any'},thresh = 1000, axis=1)
x

,Unnamed: 0,lga,Adelie Land (France)_x,Afghanistan_x,Albania_x,Algeria_x,"Americas, nfd_x",Andorra_x,Angola_x,Anguilla_x,...,Not stated_x_3,Other Religions,Advanced Diploma and Diploma Level,Bachelor Degree Level,Certificate Level,Graduate Diploma and Graduate Certificate Level,Level of education inadequately described,Level of education not stated,Not applicable,Postgraduate Degree Level
0,0,Albury (C),0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,...,4284,138,2371.0,3351.0,7381.0,571.0,587.0,4048.0,27512.0,458.0
1,1,Armidale Dumaresq (A),0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2319,135,1284.0,2351.0,2976.0,351.0,312.0,1833.0,13225.0,1046.0
2,2,Ashfield (A),0.0,4.0,0.0,8.0,0.0,0.0,0.0,0.0,...,4696,281,2715.0,6604.0,3396.0,697.0,559.0,4598.0,18417.0,2675.0
3,3,Ballina (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3515,164,2350.0,3207.0,6163.0,473.0,612.0,3202.0,21911.0,553.0
4,4,Balranald (A),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,271,3,69.0,90.0,245.0,16.0,19.0,257.0,1741.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,502,Palmerston (C),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3464,131,1573.0,1585.0,5133.0,273.0,214.0,2484.0,16144.0,289.0
503,503,Wagait (S),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,31,0,17.0,50.0,76.0,8.0,6.0,32.0,169.0,9.0
504,504,Unincorporated NT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1707,49,460.0,643.0,1501.0,111.0,71.0,1483.0,3668.0,155.0
505,505,Unincorporated ACT,0.0,345.0,20.0,32.0,0.0,0.0,17.0,0.0,...,26924,2767,26046.0,61827.0,39035.0,11142.0,4720.0,18708.0,169420.0,25686.0
506,506,Unincorp. Other Territories,0.0,112.0,0.0,0.0,0.0,0.0,0.0,0.0,...,911,59,128.0,159.0,332.0,32.0,22.0,987.0,1317.0,33.0

In [9]:
#shuffle data from 2006 and 2011 in order to split training and testing data

data_y = [data_2006_y, data_2011_y]
y_a = pd.concat(data_y)
#shuffle
X, y = shuffle(x, y_a, random_state=13)
#separate the LGA names since it is not needed for running model
#note that the LGA codes have been shuffled with the data so they will still follow the order of the model data
X_a = X.iloc[:,2:]
lgas = X.iloc[:,:2]

y_a =  y.iloc[:,1:]

In [10]:
#drop values that are not found in both census 2006 and 2011
X = X_a.dropna(how='any', axis=1)
X

,Adelie Land (France)_x,Afghanistan_x,Albania_x,Algeria_x,"Americas, nfd_x",Andorra_x,Angola_x,Anguilla_x,"Antarctica, nfd_x",Antigua and Barbuda_x,...,Not stated_x_3,Other Religions,Advanced Diploma and Diploma Level,Bachelor Degree Level,Certificate Level,Graduate Diploma and Graduate Certificate Level,Level of education inadequately described,Level of education not stated,Not applicable,Postgraduate Degree Level
106,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,605,27,298.0,360.0,1032.0,60.0,59.0,550.0,4212.0,25.0
0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4284,138,2371.0,3351.0,7381.0,571.0,587.0,4048.0,27512.0,458.0
224,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2869,47,800.0,1432.0,4247.0,131.0,161.0,2324.0,13318.0,171.0
176,0.0,16.0,8.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,8983,521,7949.0,24537.0,6021.0,2890.0,837.0,7942.0,35402.0,7579.0
215,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3283,59,1511.0,2111.0,4375.0,386.0,274.0,2819.0,18635.0,280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,348,3,225.0,316.0,633.0,34.0,22.0,289.0,2642.0,27.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2261,46,641.0,782.0,3006.0,146.0,150.0,2306.0,11357.0,123.0
74,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3223,209,2567.0,6681.0,2320.0,651.0,495.0,2573.0,12819.0,2317.0
176,0.0,7.0,25.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8062,405,4337.0,7684.0,9833.0,1214.0,813.0,7732.0,48144.0,1708.0
338,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,532,15,129.0,132.0,588.0,19.0,14.0,428.0,2419.0,12.0

In [11]:
#ensure data type is float and check that there are no nan values
X = X_a.astype(np.float32)
y_a = y_a.astype(np.float32)
np.any(np.isnan(X))

False

In [13]:
#increase Polynomial of data to increase the chances of fitting data
#this method is not used,since linear data was enough to find a fitting model
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(interaction_only=True)
X_poly = poly.fit_transform(X)

X_train_poly, X_test_poly, y_train_poly, y_test_poly = train_test_split(X_poly, y, test_size=0.2)
X_train_poly.shape

(816, 179701)

In [14]:
#split data
X_train, X_test, y_train, y_test = train_test_split(X, y_a, test_size=0.2)

#scale is not necessary since data is already into a normal distribution of values, and there are no outliers
'''
#scale training data
scaler = preprocessing.StandardScaler().fit(X_train)
X_scaled = scaler.transform(X_train)
'''
X_scaled = X_train
X_scaled.shape

(816, 599)

In [15]:
#baseline dummy model, estimating refression using the mean values
dummy_baseline_model = MultiOutputRegressor(DummyRegressor(strategy="mean")).fit(X_scaled,y_train)

dummy_predictions = dummy_baseline_model.predict(X_test)

dummy_score = r2_score(y_test,dummy_predictions,multioutput='uniform_average')
dummy_score

0.03650241629728125

## Regression algorithms to test
#### Random Forest regression
#### Lasso Regression
#### Kneighbours regreesion
#### Gaussian Processes regression
#### XGBRegressor
#### Support Vector Regression

In [16]:
#models, predictions = MultiOutputRegressor(LazyRegressor(verbose=0, ignore_warnings=False, custom_metric=None)).fit(X_scaled, X_test, y_train, y_test)
#Random Forests Regression
random_forest_model = MultiOutputRegressor(RandomForestRegressor(n_estimators = 150,warm_start=True,n_jobs= -1)).fit(X_scaled,y_train)

In [107]:
random_forest_predictions = random_forest_model.predict(X_test)
random_forest_score = r2_score(y_test,random_forest_predictions,multioutput='uniform_average')

random_forest_train_predictions = random_forest_model.predict(X_train)
random_forest_train_score = r2_score(y_train,random_forest_train_predictions,multioutput='uniform_average')
print("train r2 is:",random_forest_train_score,"test r2 is:",random_forest_score)

train r2 is: 0.9485591720023362 test r2 is: 0.5563690120952101

In [50]:
#Random Forrest using Cross Validation
from sklearn.model_selection import cross_validate
from sklearn import metrics
scoring = ['r2','neg_mean_absolute_error','neg_mean_squared_error']
scores = cross_validate(random_forest_model, X, y_a, cv=5, scoring = scoring)
scores

{'fit_time': array([370.05767536, 343.45496702, 349.54278588, 347.99656916,
        351.57909441]),
 'score_time': array([6.36816144, 6.45556378, 6.39816999, 6.38425279, 6.47711706]),
 'test_r2': array([0.62427658, 0.63821618, 0.54387322, 0.57908873, 0.59127509]),
 'test_neg_mean_absolute_error': array([-21.09814391, -21.16982859, -13.70033864, -13.3955431 ,
        -15.93733777]),
 'test_neg_mean_squared_error': array([ -771332.46274182, -1314894.7619413 ,  -143235.03977732,
          -79052.23551963,  -150403.24938902])}

In [51]:
print(scores['test_r2'])
print(scores['test_neg_mean_absolute_error'])
print(scores['test_neg_mean_squared_error'])

[0.62427658 0.63821618 0.54387322 0.57908873 0.59127509]
[-21.09814391 -21.16982859 -13.70033864 -13.3955431  -15.93733777]
[ -771332.46274182 -1314894.7619413   -143235.03977732   -79052.23551963
  -150403.24938902]

In [27]:
#Random Forrest using a pipeline that scales, transforms and runs models in CV
from sklearn.decomposition import PCA
pca = PCA(n_components=100)
x_pca = pca.fit_transform(X)
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(x_pca, y_a, test_size=0.2)
random_forest_model_pca = MultiOutputRegressor(RandomForestRegressor(n_estimators = 150,n_jobs= -1)).fit(X_train_pca,y_train)

train r2 is: -0.1402156862671659 test r2 is: -0.974474511844048

In [29]:
from sklearn.metrics import mean_absolute_error

random_forest_train_predictions_pca = random_forest_model_pca.predict(X_train_pca)
random_forest_train_score_pca = r2_score(y_train_pca,random_forest_train_predictions_pca,multioutput='uniform_average')
random_forest_predictions_pca = random_forest_model_pca.predict(X_test_pca)
random_forest_score_pca = r2_score(y_test_pca,random_forest_predictions_pca,multioutput='uniform_average')

random_forest_train_scoremae_pca = mean_absolute_error(y_train_pca,random_forest_train_predictions_pca,multioutput='uniform_average')
random_forest_scoremae_pca = mean_absolute_error(y_test_pca,random_forest_predictions_pca,multioutput='uniform_average')

print("train r2 is:",random_forest_train_score_pca,"test r2 is:",random_forest_score_pca)
print("train mean absolute error is:",random_forest_train_scoremae_pca,"test mean absolute error is:",random_forest_scoremae_pca)

train r2 is: -0.1402156862671659 test r2 is: -0.974474511844048
train mean absolute error is: 169.41540300900232 test mean absolute error is: 164.54776112960906

In [84]:
#K Neighbours regressor
KNN_reg_model = MultiOutputRegressor(KNeighborsRegressor(n_neighbors=10,n_jobs=-1)).fit(X_scaled,y_train)

In [85]:
KNN_predictions = KNN_reg_model.predict(X_test)
KNN_score = r2_score(y_test,KNN_predictions,multioutput='uniform_average')



KNN_train_predictions = KNN_reg_model.predict(X_train)
knn_train_score = r2_score(y_train,KNN_train_predictions,multioutput='uniform_average')
print("train acuracy is:",knn_train_score,"test acuracy is:",KNN_score)

train acuracy is: 0.47255897693909277 test acuracy is: 0.35730348642687654

In [33]:
#KNN again but now with PCA
KNN_reg_model_pca = MultiOutputRegressor(KNeighborsRegressor(n_neighbors=25,n_jobs=-1)).fit(X_train_pca,y_train)


KNN_predictions_pca = KNN_reg_model_pca.predict(X_test_pca)
KNN_train_predictions_pca = KNN_reg_model_pca.predict(X_train_pca)
#r2
KNN_score_pca = r2_score(y_test_pca,KNN_predictions_pca,multioutput='uniform_average')
knn_train_score_pca = r2_score(y_train_pca,KNN_train_predictions_pca,multioutput='uniform_average')
#mae
KNN_scoremae_pca = mean_absolute_error(y_test_pca,KNN_predictions_pca,multioutput='uniform_average')
knn_train_scoremae_pca = mean_absolute_error(y_train_pca,KNN_train_predictions_pca,multioutput='uniform_average')


print("train acuracy is:",knn_train_score_pca,"test acuracy is:",KNN_score_pca)
print("train mean absolute error is:",knn_train_scoremae_pca,"test mean absolute error is:",KNN_scoremae_pca)

train acuracy is: 0.048475200969125755 test acuracy is: -0.022488659688217925
train mean absolute error is: 183.56119 test mean absolute error is: 186.04681

In [108]:

GP_reg_model = MultiOutputRegressor(GaussianProcessRegressor()).fit(X_scaled,y_train)

In [109]:
GP_predictions = GP_reg_model.predict(X_test)
GP_score = r2_score(y_test,GP_predictions,multioutput='uniform_average')


GP_train_predictions = GP_reg_model.predict(X_train)
GP_train_score = r2_score(y_train,GP_train_predictions,multioutput='uniform_average')
print("train acuracy is:",GP_train_score,"test acuracy is:",GP_score)

train acuracy is: 1.0 test acuracy is: 0.10175316517015265

In [110]:
xgb_model = MultiOutputRegressor(XGBRegressor()).fit(X_scaled,y_train)

In [111]:
xgb_predictions = xgb_model.predict(X_test)
xgb_score = r2_score(y_test,xgb_predictions,multioutput='uniform_average')


xgb_train_predictions = xgb_model.predict(X_train)
xgb_train_score = r2_score(y_train,xgb_train_predictions,multioutput='uniform_average')
print("train acuracy is:",xgb_train_score,"test acuracy is:",xgb_score)

train acuracy is: 0.8943395302984782 test acuracy is: 0.17024185551867294

In [20]:
svr_model = MultiOutputRegressor(SVR()).fit(X_scaled,y_train)

In [21]:
svr_predictions = svr_model.predict(X_test)
svr_score = r2_score(y_test,svr_predictions,multioutput='uniform_average')


svr_train_predictions = svr_model.predict(X_train)
svr_train_score = r2_score(y_train,svr_train_predictions,multioutput='uniform_average')
print("train acuracy is:",svr_train_score,"test acuracy is:",svr_score)

train acuracy is: 0.2570505037227398 test acuracy is: 0.24545603804632465

In [37]:
from sklearn.model_selection import GridSearchCV
parameters_RForest={'estimator__n_estimators':[100,150,200],'estimator__warm_start':[True],'estimator__n_jobs':[-1]}
clf = GridSearchCV(random_forest_model, parameters_RForest)
clf.get_params().keys()
clf.fit(X_scaled,y_train)

GridSearchCV(estimator=MultiOutputRegressor(estimator=RandomForestRegressor(n_jobs=-1,
                                                                            warm_start=True)),
             param_grid={'estimator__n_estimators': [100, 150, 200],
                         'estimator__n_jobs': [-1],
                         'estimator__warm_start': [True]})

In [38]:
clf.cv_results_

{'mean_fit_time': array([163.97030931, 230.859939  , 271.98125224]),
 'std_fit_time': array([ 3.89506955, 12.88862106,  3.59285856]),
 'mean_score_time': array([ 8.63330836, 12.09079723, 14.28348241]),
 'std_score_time': array([0.08004077, 1.05785563, 0.11956017]),
 'param_estimator__n_estimators': masked_array(data=[100, 150, 200],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'param_estimator__n_jobs': masked_array(data=[-1, -1, -1],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'param_estimator__warm_start': masked_array(data=[True, True, True],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'estimator__n_estimators': 100,
   'estimator__n_jobs': -1,
   'estimator__warm_start': True},
  {'estimator__n_estimators': 150,
   'estimator__n_jobs': -1,
   'estimator__warm_start': True},
  {'estimator__n_estimators': 200,
   'estimator__n_jobs': -1,
   'estimator__warm_start': True}],
 'split0_test_score': array([0.67152149, 0.67596701, 0.69101186]),
 'split1_test_score': array([0.60779802, 0.61711302, 0.60483884]),
 'split2_test_score': array([0.57323871, 0.5742042 , 0.57026618]),
 'split3_test_score': array([0.81909688, 0.82648011, 0.81557458]),
 'split4_test_score': array([0.83519761, 0.83862019, 0.83330695]),
 'mean_test_score': array([0.70137054, 0.7064769 , 0.70299968]),
 'std_test_score': array([0.1075488 , 0.10795874, 0.1068181 ]),
 'rank_test_score': array([3, 1, 2])}

In [39]:
clf.best_params_

{'estimator__n_estimators': 150,
 'estimator__n_jobs': -1,
 'estimator__warm_start': True}

### Stacking succesful classifiers

In [62]:
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import GradientBoostingRegressor
rf=RandomForestRegressor(warm_start = True,n_estimators = 150)
gp = GaussianProcessRegressor()
xgb =XGBRegressor(warm_start = True)
estimators = [('rf',rf),('gp',gp),('xgb',xgb)]
final_estimator = GradientBoostingRegressor(warm_start = False,n_estimators=200,subsample=1, min_samples_leaf=25,random_state=42,criterion='mae')
#stacked_reg = StackingRegressor(estimators=estimators,final_estimator=final_estimator,n_jobs=-1, cv=5)

stacked_f_reg = MultiOutputRegressor(StackingRegressor(estimators=estimators,final_estimator=final_estimator,n_jobs=-1, cv=5)).fit(X_train, y_train)

In [58]:
#stacked_f_reg

stacked_f_reg_predictions = stacked_f_reg.predict(X_train)
stacked_f_reg_predictions_test = stacked_f_reg.predict(X_test)

stacked_f_reg_predictions_score = r2_score(y_train,stacked_f_reg_predictions,multioutput='uniform_average')
stacked_f_reg_predictions_test_score_test = r2_score(y_test,stacked_f_reg_predictions_test,multioutput='uniform_average')

#stacked_f_reg_predictions_scoremae = mean_absolute_error(y_train,stacked_f_reg_predictions_score,multioutput='uniform_average')
stacked_f_reg_predictions_test_scoremae = mean_absolute_error(y_test,stacked_f_reg_predictions_test,multioutput='uniform_average')

print("train r2 is:",stacked_f_reg_predictions_score,"test r2 is:",stacked_f_reg_predictions_test_score_test)
#print("train mean absolute error is:",stacked_f_reg_predictions_scoremae,"test mean absolute error is:",stacked_f_reg_predictions_test_scoremae)

train r2 is: 0.4227940598063618 test r2 is: 0.44100568448634914

In [68]:
from sklearn.ensemble import VotingRegressor
estimators = [('rf',random_forest_model),('gp',GP_reg_model),('xgb',xgb_model), ('knn',KNN_reg_model)]
ereg = VotingRegressor(estimators=estimators)
ereg = ereg.fit(X_train, y_train)

TypeError: 'VotingRegressor' object is not callable

In [71]:
from sklearn.neural_network import MLPRegressor

mlp = MultiOutputRegressor(MLPRegressor(warm_start = True, activation = 'linear',)).fit(X_train, y_train)

In [72]:
mlp_predictions = mlp.predict(X_test)
mlp_score = r2_score(y_test,mlp_predictions,multioutput='uniform_average')

mlp_train_predictions = mlp.predict(X_train)
mlp_train_score = r2_score(y_train,mlp_train_predictions,multioutput='uniform_average')
print("train acuracy is:",mlp_train_score,"test acuracy is:",mlp_score)

train acuracy is: -789851.3830149428 test acuracy is: -215294.79429543504

In [104]:
#SUM PREDICTIONS AND AVERAGE THE RESULT OF THE MODELS TO GENERATE A STACKED VERSION
sum_predictions = np.add(random_forest_predictions, GP_predictions,xgb_predictions)
avg_predictions = sum_predictions / 3

sum_train_predictions = np.add(random_forest_train_predictions, GP_train_predictions,xgb_train_predictions)
avg_train_predictions = sum_train_predictions / 3

stack_train_score = r2_score(y_train,avg_train_predictions,multioutput='uniform_average')
stack_score = r2_score(y_test,avg_predictions,multioutput='uniform_average')


print("train r2 is:",stack_train_score,"test r2 is:",stack_score)

train r2 is: 0.8583185310941742 test r2 is: 0.3686185259467774

In [105]:
from joblib import dump, load

dump(random_forest_model,'random_forest_clf.joblib')
dump(GP_reg_model,'gaussian_processReg_model.joblib')
dump(xgb_model,'xgb_clf.joblib')

['xgb_clf.joblib']